system-view

hostname S5120V3-28S-PWR-LI

lldp global enable

stp mode pvst 

stp vlan 1 enable 

vlan 1
 description VLAN-1-MANAGEMENT
quit

interface Vlan-interface 1
ip address dhcp-alloc
quit

ip route-static 0.0.0.0 0 10.100.73.1

dns server 8.8.8.8

snmp-agent
snmp-agent community intelbras123 user-role network-admin
snmp-agent sys-info version all
snmp-agent

local-user ped class manage
 password simple Admin@1234
 authorization-attribute user-role network-admin
 service-type telnet http https pad ssh terminal
quit

ssh server enable
ssh user ped service-type all authentication-type password

telnet server enable
netconf ssh server enable

line vty 0 63
authentication-mode scheme
user-role network-admin
quit

ip http enable
ntp-service enable
ntp-service unicast-server 200.160.7.186
clock timezone Brazil minus 03:00:00

info-center loghost 10.100.73.8

scp server enable

save force


